### ISSUE TITLE
Error installing ToolbarControl with CKAN

### ISSUE THREAD

**Issue by crimsonblod** [linuxgurugamer/ToolbarControl#18]
I get this error whenever I install this mod via CKAN.

```CKAN.InvalidModuleFileKraken: ToolbarController 1:0.1.9.4: C:\Users\Chris\AppData\Local\CKAN\downloads\downloading\6A56C4B2-ToolbarController-1-0.1.9.4.zip has length 88369, should be 107848
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)

**Comment by linuxgurugamer** [comment]
That's a CKAN error, you need to contact the CKAN group:
https://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1180-19-june-2016/
